/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppNotePad;

import java.util.Arrays;
import java.util.Objects;

/**
 *
 * @author Thuan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncryption = new javax.swing.JButton();
        lblKeyEncryption = new javax.swing.JLabel();
        txtKeyEncryption = new javax.swing.JTextField();
        btnGenerateKey = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tareaGenerateKeyEncryption = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tareaEcryption = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tereaDecryption = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaKeyDecryption = new javax.swing.JTextArea();
        btnDecryption = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtKeyDecryption = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEncryption.setText("Encryption");
        btnEncryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptionActionPerformed(evt);
            }
        });

        lblKeyEncryption.setText("Key");

        txtKeyEncryption.setName("txtKeyEncryption"); // NOI18N

        btnGenerateKey.setText("Generate Key");
        btnGenerateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKeyActionPerformed(evt);
            }
        });

        tareaGenerateKeyEncryption.setColumns(20);
        tareaGenerateKeyEncryption.setRows(5);
        jScrollPane4.setViewportView(tareaGenerateKeyEncryption);

        tareaEcryption.setColumns(20);
        tareaEcryption.setRows(5);
        jScrollPane3.setViewportView(tareaEcryption);

        tereaDecryption.setColumns(20);
        tereaDecryption.setRows(5);
        jScrollPane2.setViewportView(tereaDecryption);

        tareaKeyDecryption.setColumns(20);
        tareaKeyDecryption.setRows(5);
        jScrollPane1.setViewportView(tareaKeyDecryption);

        btnDecryption.setText("Decryption");
        btnDecryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptionActionPerformed(evt);
            }
        });

        jLabel2.setText("Key");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(705, Short.MAX_VALUE)
                        .addComponent(btnDecryption, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(105, 105, 105))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKeyDecryption, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKeyEncryption)
                                .addGap(36, 36, 36)
                                .addComponent(txtKeyEncryption))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerateKey, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(btnEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKeyEncryption)
                            .addComponent(txtKeyEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEncryption)
                            .addComponent(btnGenerateKey))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKeyDecryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDecryption))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptionActionPerformed
        // TODO add your handling code here:
        String keyEncryption = txtKeyEncryption.getText().toLowerCase().replaceAll("\\s{1,}", "").trim();
        String[][] key = generateKey(keyEncryption);
        String plainText = tareaEcryption.getText().toLowerCase().replaceAll("\\s{1,}", "").trim();

        String splitInput = sperateStringEncryption(plainText,2);
        String cipherText = encryption(splitInput, key);

        tereaDecryption.setText(cipherText);
    }//GEN-LAST:event_btnEncryptionActionPerformed

    private void btnGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateKeyActionPerformed
        // TODO add your handling code here:
        String keyEncryption = txtKeyEncryption.getText().toLowerCase().replaceAll("\\s{1,}", "").trim();
        String[][] key = generateKey(keyEncryption);
        tareaGenerateKeyEncryption.setText(Arrays.deepToString(key).replace("[", "").replace("]", "").replace(",",""));
    }//GEN-LAST:event_btnGenerateKeyActionPerformed

    private void btnDecryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptionActionPerformed
        // TODO add your handling code here:
        String keyEncryption = txtKeyEncryption.getText().toLowerCase().replaceAll("\\s{1,}", "").trim();
        String keyDecryption = Objects.equals(txtKeyDecryption.getText().trim(), "") ? keyEncryption : txtKeyDecryption.getText().toLowerCase().replaceAll("\\s{1,}", "").trim();
        String[][] key = generateKey(keyDecryption);
        String cipherText = tereaDecryption.getText().toLowerCase().toLowerCase().replaceAll("\\s{1,}", "").trim();
        
        String cipherTextInput = sperateStringDecryption(cipherText, 2);
        String plainText = decryption(cipherTextInput, key);
        tareaKeyDecryption.setText(Arrays.deepToString(key).replace("[", "").replace("]", "").replace(",",""));
        tareaEcryption.setText(plainText);
    }//GEN-LAST:event_btnDecryptionActionPerformed
   
   private String sperateStringEncryption(String stringInput, int numberSplitWord){
        String result = "";
        String[] stringInputArr = stringInput.split("");
 
        String prevWord = "";
        String randomWord = "x";
        //split two word and re arrange 
        for(int counter =0; counter < stringInput.length(); counter++){
            if(Objects.equals(stringInputArr[counter], prevWord)){
                result += randomWord;
                result += stringInputArr[counter];
                prevWord = stringInputArr[counter];
            }
            else{
                result += stringInputArr[counter];
                prevWord = stringInputArr[counter];
            }
        }
        
        return result.length() % 2 == 0 ? result: (result + randomWord);
    }
   private String sperateStringDecryption(String stringInput, int numberSplitWord){
        String result = "";
        String[] stringInputArr = stringInput.split("");
 
        String prevWord = "";
        String randomWord = "y";
        //split two word and re arrange 
        for(int counter =0; counter < stringInput.length(); counter++){
            if(Objects.equals(stringInputArr[counter], prevWord)){
                result += randomWord;
                result += stringInputArr[counter];
                prevWord = stringInputArr[counter];
            }
            else{
                result += stringInputArr[counter];
                prevWord = stringInputArr[counter];
            }
        }
        
        return result.length() % 2 == 0 ? result: (result + randomWord);
    }
    //work well
    private String[][] generateKey(String key){
        String[][] keyResult = new String[5][5];
        int col =0;
        int row = 0;
        String[] keyBaseGenerate = keyBase.split("");
        
        //distinct key Encryption
        String[] keyInput = Arrays.stream(key.split("")).distinct().toArray(String[]::new);
        boolean containsI = Arrays.stream(keyInput).anyMatch("i"::equals);
        boolean containsJ = Arrays.stream(keyInput).anyMatch("j"::equals);

        //Fillter keyBase
        for(int counter = 0; counter < keyInput.length; counter++){
            for(int index = 0; index < keyBaseGenerate.length; index++){
                if(Objects.equals(keyInput[counter], keyBaseGenerate[index])){
                    keyBaseGenerate[index] = null;
                }
            }
        }
        
        for(int counter = 0; counter < keyInput.length; ){
            if(col == 5){
                row += 1;
                col = 0;
            }
            if(Objects.equals(keyInput[counter], "j")){
                if(containsI && containsJ){
                    counter++;
                }
            }
            keyResult[row][col] = keyInput[counter];
            col++;
            counter++;
        }
        
            for(int counter = 0; counter < keyBaseGenerate.length;){
                if(col == 5 && row < 5){
                    row += 1;
                    col = 0;
                    if(row == 5){
                        break;
                    }
                }
                if(keyBaseGenerate[counter] == null){
                    counter++;
                }
                else{
                    keyResult[row][col] = keyBaseGenerate[counter];
                    col++;
                    counter++;
                }
                
           }

        return keyResult;
    }
    
    private String encryption(String preEncryptionText, String[][] key){
        String result = "";
        // same row +1 to the right, the col +1 to down side and final ref to index of eachother
        //if the plaintext split two word is dulicapte we have to insert into this the random word
        //matrix 5x5
        String indexFirstWord = "";
        String indexSecondWord ="";
        String[] plainText = preEncryptionText.split("");

        for(int counter = 0; counter < preEncryptionText.length(); counter = counter+2){
            for(int row =0; row < key.length; row++){
                for(int col = 0; col < key.length; col++){
                    int isFoundTwoWord = 0;
                    if(Objects.equals(key[row][col], plainText[counter])){
                        indexFirstWord = String.valueOf(row) + String.valueOf(col);
                        isFoundTwoWord++;
                        
                    }
                     if(Objects.equals(key[row][col], plainText[counter+1])){
                        indexSecondWord = String.valueOf(row) + String.valueOf(col);
                        isFoundTwoWord++;
                    }
                    if(isFoundTwoWord == 2) break;
                }
            }
            String[] indexFirstRowCol = indexFirstWord.split("");
            String[] indexSecondRowCol = indexSecondWord.split("");
            if(Objects.equals(indexFirstRowCol[0], indexSecondRowCol[0])){
                //same row
                int colFirstWord = Integer.parseInt(indexFirstRowCol[1]) == 4 ? colFirstWord = 0 : Integer.parseInt(indexFirstRowCol[1]) + 1;
                int colSecondWord = Integer.parseInt(indexSecondRowCol[1]) == 4 ? colSecondWord = 0 : Integer.parseInt(indexSecondRowCol[1]) + 1;
                result += key[Integer.parseInt(indexFirstRowCol[0])][colFirstWord];
                result += key[Integer.parseInt(indexSecondRowCol[0])][colSecondWord];

            }
            else if(Objects.equals(indexFirstRowCol[1], indexSecondRowCol[1])){
                int rowFirstWord = Integer.parseInt(indexFirstRowCol[0]) == 4 ? rowFirstWord = 0 : Integer.parseInt(indexFirstRowCol[0]) + 1;
                int rowSecondWord = Integer.parseInt(indexSecondRowCol[0]) == 4 ? rowSecondWord = 0 : Integer.parseInt(indexSecondRowCol[0]) + 1;
                result += key[rowFirstWord][Integer.parseInt(indexFirstRowCol[1])];
                result += key[rowSecondWord][Integer.parseInt(indexSecondRowCol[1])];
            }
            else{
                int colFirstWord = Integer.parseInt(indexFirstRowCol[1]);
                int colSecondWord = Integer.parseInt(indexSecondRowCol[1]);
                result += key[Integer.parseInt(indexFirstRowCol[0])][colSecondWord];
                result += key[Integer.parseInt(indexSecondRowCol[0])][colFirstWord];
            }
        }
        return result; 
    }
    
    private String decryption(String preDecryptionText, String[][] key){
    String result = "";
        // same row +1 to the right, the col +1 to down side and final ref to index of eachother
        //if the plaintext split two word is dulicapte we have to insert into this the random word
        //matrix 5x5
        String indexFirstWord = "";
        String indexSecondWord ="";
        String[] plainText = preDecryptionText.split("");

        for(int counter = 0; counter < preDecryptionText.length(); counter = counter+2){
            for(int row =0; row < key.length; row++){
                for(int col = 0; col < key.length; col++){
                    int isFoundTwoWord = 0;
                    if(Objects.equals(key[row][col], plainText[counter])){
                        indexFirstWord = String.valueOf(row) + String.valueOf(col);
                        isFoundTwoWord++;
                        
                    }
                     if(Objects.equals(key[row][col], plainText[counter+1])){
                        indexSecondWord = String.valueOf(row) + String.valueOf(col);
                        isFoundTwoWord++;
                    }
                    if(isFoundTwoWord == 2) break;
                }
            }
            String[] indexFirstRowCol = indexFirstWord.split("");
            String[] indexSecondRowCol = indexSecondWord.split("");
            if(Objects.equals(indexFirstRowCol[0], indexSecondRowCol[0])){
                //same row
                int colFirstWord = Integer.parseInt(indexFirstRowCol[1]) == 0 ? colFirstWord = 4 : Integer.parseInt(indexFirstRowCol[1]) - 1;
                int colSecondWord = Integer.parseInt(indexSecondRowCol[1]) == 0 ? colSecondWord = 4 : Integer.parseInt(indexSecondRowCol[1]) -1;
                result += key[Integer.parseInt(indexFirstRowCol[0])][colFirstWord];
                result += key[Integer.parseInt(indexSecondRowCol[0])][colSecondWord];

            }
            else if(Objects.equals(indexFirstRowCol[1], indexSecondRowCol[1])){
                int rowFirstWord = Integer.parseInt(indexFirstRowCol[0]) == 0 ? rowFirstWord = 4 : Integer.parseInt(indexFirstRowCol[0]) - 1;
                int rowSecondWord = Integer.parseInt(indexSecondRowCol[0]) == 0 ? rowSecondWord = 4 : Integer.parseInt(indexSecondRowCol[0]) - 1;
                result += key[rowFirstWord][Integer.parseInt(indexFirstRowCol[1])];
                result += key[rowSecondWord][Integer.parseInt(indexSecondRowCol[1])];
            }
            else{
                int colFirstWord = Integer.parseInt(indexFirstRowCol[1]);
                int colSecondWord = Integer.parseInt(indexSecondRowCol[1]);
                result += key[Integer.parseInt(indexFirstRowCol[0])][colSecondWord];
                result += key[Integer.parseInt(indexSecondRowCol[0])][colFirstWord];
            }
        }
        return result; 
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecryption;
    private javax.swing.JButton btnEncryption;
    private javax.swing.JButton btnGenerateKey;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblKeyEncryption;
    private javax.swing.JTextArea tareaEcryption;
    private javax.swing.JTextArea tareaGenerateKeyEncryption;
    private javax.swing.JTextArea tareaKeyDecryption;
    private javax.swing.JTextArea tereaDecryption;
    private javax.swing.JTextField txtKeyDecryption;
    private javax.swing.JTextField txtKeyEncryption;
    // End of variables declaration//GEN-END:variables
    private String keyBase = "abcdefghiklmnopqrstuvwxyz";

}
